package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Friday, 17 March 2017 14:05:41 o'clock CET
*/

public interface ChatOperations 
{
  String say (ChatApp.ChatCallback objref, String message);
  String join (ChatApp.ChatCallback objref, String message);
  String list (ChatApp.ChatCallback objref);
  void leave (ChatApp.ChatCallback objref);
  void post (ChatApp.ChatCallback objref, String message);
  void printBoard (ChatApp.ChatCallback objref);
  void init (ChatApp.ChatCallback objref);
  void put (ChatApp.ChatCallback objref, String message);
} // interface ChatOperations
